import { Archive, ChevronLeft, ChevronRight, CircleHelp, FileText, LayoutDashboard, Plus, Scale, Settings, ShieldCheck } from "lucide-react";
import { motion } from "framer-motion";
import { NavLink } from "react-router-dom";
import { Brand } from "./Brand";

const links = [["/dashboard", "Overview", LayoutDashboard], ["/contracts/new", "New contract", Plus], ["/disputes", "Disputes", Scale], ["/reputation", "Reputation", ShieldCheck], ["/settings", "Settings", Settings]] as const;
export function Sidebar({ collapsed, onToggle }: { collapsed: boolean; onToggle: () => void }) {
  return <motion.aside animate={{ width: collapsed ? 76 : 232 }} transition={{ duration: .2 }} className="sticky top-5 hidden h-[calc(100vh-40px)] shrink-0 flex-col rounded-2xl bg-ink/55 p-3 ringline soft-card lg:flex">
    <div className="flex items-center justify-between px-1 pb-6"><Brand compact={collapsed} /><button onClick={onToggle} aria-label={collapsed ? "Expand sidebar" : "Collapse sidebar"} className="grid h-8 w-8 place-items-center rounded-lg text-white/45 transition hover:bg-white/8 hover:text-cream">{collapsed ? <ChevronRight size={17} /> : <ChevronLeft size={17} />}</button></div>
    <nav className="space-y-1" aria-label="Workspace">{links.map(([to, label, Icon]) => <NavLink key={to} to={to} title={collapsed ? label : undefined} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-3 text-[12px] font-semibold transition ${isActive ? "bg-mint/12 text-mint ringline" : "text-white/55 hover:bg-white/6 hover:text-cream"}`}><Icon size={18} /><span className={collapsed ? "sr-only" : ""}>{label}</span></NavLink>)}</nav>
    <div className="mt-auto space-y-2"><NavLink to="/contracts" title={collapsed ? "Contracts" : undefined} className="flex items-center gap-3 rounded-xl px-3 py-3 text-[12px] font-semibold text-white/55 transition hover:bg-white/6 hover:text-cream"><FileText size={18} /><span className={collapsed ? "sr-only" : ""}>Contracts</span></NavLink><NavLink to="/archive" title={collapsed ? "Archive" : undefined} className="flex items-center gap-3 rounded-xl px-3 py-3 text-[12px] font-semibold text-white/55 transition hover:bg-white/6 hover:text-cream"><Archive size={18} /><span className={collapsed ? "sr-only" : ""}>Archive</span></NavLink>{!collapsed && <div className="mt-2 rounded-xl bg-white/[.035] p-3 ringline"><div className="flex items-center gap-2 text-[11px] font-semibold text-white/75"><CircleHelp size={15} className="text-mint" />Need a hand?</div><p className="mt-1.5 text-[10px] leading-4 text-white/40">Escrow questions or a contract issue?</p></div>}</div>
  </motion.aside>;
}
