import { ArrowRight, Check, CirclePlay, LockKeyhole, Scale, Sparkles, Wallet } from "lucide-react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { Brand } from "../components/Brand";

const steps = [["1", "Fund a milestone", "Client locks funds into a Stellar escrow contract."], ["2", "Show the work", "Freelancer submits evidence against the agreed scope."], ["3", "Release fairly", "AI assists review, while people retain final control."]];
export function Landing() {
  return <div className="min-h-screen bg-teal text-cream"><header className="absolute inset-x-0 top-0 z-20"><div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 sm:px-8"><Brand /><nav className="hidden items-center gap-7 text-[13px] font-medium text-white/70 md:flex"><a href="#how-it-works" id="landing-how-link" className="transition hover:text-cream">How it works</a><a href="#trust" id="landing-trust-link" className="transition hover:text-cream">Trust & safety</a><Link to="/dashboard" className="transition hover:text-cream">Sign in</Link></nav><Link to="/dashboard" className="rounded-full bg-mint px-4 py-2.5 text-[12px] font-bold text-ink shadow-mint transition hover:brightness-105">Open workspace</Link></div></header>
    <main><section className="landing-hero relative flex min-h-[760px] items-end overflow-hidden px-5 pb-16 pt-28 sm:px-8 lg:min-h-[800px] lg:pb-24"><div className="absolute inset-x-0 bottom-0 h-64 bg-gradient-to-t from-teal to-transparent" /><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55 }} className="relative mx-auto w-full max-w-[1440px]"><div className="max-w-3xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-mint/12 px-3 py-2 text-[11px] font-bold text-mint ringline"><span className="h-1.5 w-1.5 rounded-full bg-mint dot-pulse" />Stellar-powered milestone escrow</div><h1 className="max-w-3xl text-5xl font-extrabold leading-[.96] tracking-[-.065em] sm:text-7xl lg:text-[88px]">Where milestones meet money—<span className="text-mint">instantly, fairly, on-chain.</span></h1><p className="mt-7 max-w-xl text-[16px] leading-7 text-white/74">Meridian makes freelance work safer with escrowed payments, AI-assisted review, and neutral dispute briefs—built on Stellar.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/dashboard" className="flex items-center gap-2 rounded-full bg-mint px-5 py-3.5 text-[13px] font-bold text-ink shadow-mint transition hover:brightness-105">Start a contract <ArrowRight size={16} /></Link><a id="landing-demo-link" href="#how-it-works" className="flex items-center gap-2 rounded-full bg-white/7 px-5 py-3.5 text-[13px] font-semibold text-white ringline transition hover:bg-white/12"><CirclePlay size={17} className="text-mint" />See how it works</a></div></div></motion.div></section>
      <section id="trust" className="border-y border-white/10 bg-ink/35"><div className="mx-auto grid max-w-[1440px] gap-5 px-5 py-7 sm:grid-cols-3 sm:px-8"><TrustItem icon={<LockKeyhole size={18} />} title="Funds held on-chain" detail="Escrow state lives in Soroban contracts, not a private ledger." /><TrustItem icon={<Sparkles size={18} />} title="AI informs, never decides" detail="Review signals are visible to both sides; approvals always remain human." /><TrustItem icon={<Scale size={18} />} title="Disputes stay balanced" detail="Evidence is turned into a neutral brief for the designated arbitrator." /></div></section>
      <section id="how-it-works" className="mx-auto max-w-[1440px] px-5 py-24 sm:px-8"><div className="max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-mint">A clear path to paid</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.055em] sm:text-5xl">A better agreement from day one.</h2><p className="mt-5 text-[15px] leading-7 text-white/65">Every milestone is explicit, funded, and visible. That means fewer surprises for clients and a fairer path to payment for freelancers.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{steps.map(([number, title, detail], index) => <motion.article initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .08 }} key={title} className="rounded-3xl bg-surface/50 p-6 ringline soft-card"><span className="grid h-10 w-10 place-items-center rounded-xl bg-mint text-sm font-extrabold text-ink">{number}</span><h3 className="mt-10 text-xl font-bold">{title}</h3><p className="mt-3 text-[13px] leading-6 text-white/60">{detail}</p></motion.article>)}</div></section>
      <section className="mx-5 mb-6 overflow-hidden rounded-3xl bg-[#0a2a2b] ringline sm:mx-8"><div className="grain mx-auto grid max-w-[1440px] gap-12 px-6 py-16 sm:px-10 lg:grid-cols-[1fr_.9fr] lg:px-16"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-mint">Work with confidence</p><h2 className="mt-4 max-w-xl text-4xl font-extrabold tracking-[-.055em] sm:text-5xl">The calm infrastructure behind great work.</h2><p className="mt-5 max-w-lg text-[15px] leading-7 text-white/65">Create a contract, fund the milestones, and let Meridian keep the evidence, events, and expectations in one place.</p><Link to="/dashboard" className="mt-8 inline-flex items-center gap-2 rounded-full bg-mint px-5 py-3.5 text-[13px] font-bold text-ink shadow-mint">Open your workspace <ArrowRight size={16} /></Link></div><div className="rounded-2xl bg-white/[.045] p-5 ringline soft-card"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-[12px] font-bold"><Wallet size={17} className="text-mint" />Freighter connected</div><span className="text-[11px] font-bold text-mint">Live</span></div><div className="mt-8 rounded-xl bg-ink/65 p-5 ringline"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-white/42">Available to release</p><p className="mt-2 text-4xl font-extrabold tracking-[-.055em]">$6,840<span className="text-white/35">.00</span></p><div className="mt-5 flex items-center gap-2 text-[11px] text-white/55"><Check size={15} className="text-mint" />Evidence reviewed · Client approval required</div></div></div></div></section>
    </main><footer className="mx-auto flex max-w-[1440px] flex-col gap-4 px-5 py-8 text-[11px] text-white/45 sm:flex-row sm:items-center sm:justify-between sm:px-8"><Brand /><p>© 2026 Meridian. Milestone escrow for work that matters.</p><div className="flex gap-4"><a id="footer-privacy-link" href="#trust">Privacy</a><a id="footer-terms-link" href="#trust">Terms</a></div></footer></div>;
}
function TrustItem({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="flex gap-3"><span className="mt-0.5 text-mint">{icon}</span><div><p className="text-[12px] font-bold">{title}</p><p className="mt-1 text-[11px] leading-5 text-white/55">{detail}</p></div></div>; }
