import { BellRing, CheckCircle2, Globe2, ShieldCheck, Wallet } from "lucide-react";
import { motion } from "framer-motion";
import { useState } from "react";
import { useWallet } from "../components/WalletProvider";
import { bootstrapProtocolWithFreighter, configuredFactoryAddress } from "../lib/wallet";

const compact = (address: string) => `${address.slice(0, 6)}…${address.slice(-5)}`;

export function Settings() {
  const { session, connect, connecting, disconnect } = useWallet();
  const [message, setMessage] = useState("");
  const [bootstrapping, setBootstrapping] = useState(false);
  const copyAddress = async () => { if (!session) return; await navigator.clipboard.writeText(session.address); setMessage("Wallet address copied."); };
  const config = ["VITE_API_URL", "VITE_SOROBAN_RPC_URL", "VITE_TOKEN_CONTRACT_ADDRESS"];
  const missing = config.filter((name) => !import.meta.env[name]);
  const boot = async () => { try { const wallet = session ?? await connect(); setBootstrapping(true); const deployed = await bootstrapProtocolWithFreighter({ session: wallet, tokenAddress: import.meta.env.VITE_TOKEN_CONTRACT_ADDRESS, onStatus: setMessage }); setMessage(`Protocol confirmed. Factory address: ${deployed.factoryAddress}. Add it to Vercel as VITE_FACTORY_CONTRACT_ADDRESS for every user.`); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "The protocol was not deployed."); } finally { setBootstrapping(false); } };
  const factory = configuredFactoryAddress();
  return <div className="mx-auto max-w-3xl"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-mint">Workspace preferences</p><h1 className="mt-3 text-3xl font-extrabold tracking-[-.055em]">Settings.</h1><div className="mt-8 space-y-3"><Setting icon={<Wallet size={17} />} title="Connected wallet" detail={session ? `${compact(session.address)} · Freighter` : "No wallet connected"} action={session ? "Copy address" : connecting ? "Connecting…" : "Connect"} onClick={() => { if (session) void copyAddress(); else void connect().catch((cause) => setMessage(cause instanceof Error ? cause.message : "Could not connect Freighter.")); }} /><Setting icon={<Globe2 size={17} />} title="Network" detail={session ? "Stellar Testnet · enforced for this deployment" : "Connect Freighter to validate the active network"} action="Open Freighter" onClick={() => setMessage("Switch networks from the Freighter extension. Meridian only prepares Testnet transactions in this deployment.")} /><Setting icon={<BellRing size={17} />} title="Event notifications" detail="Live on-chain event stream while this workspace is open" action="Enabled" onClick={() => setMessage("The live event stream is active in this browser session. Browser push notifications are not configured in this deployment.")} /><Setting icon={<ShieldCheck size={17} />} title="Deployment readiness" detail={missing.length ? `${missing.length} required Vercel environment variable${missing.length === 1 ? " is" : "s are"} missing.` : factory ? `Factory ${compact(factory)} is ready.` : "Protocol has not been initialized yet."} action={missing.length ? "Review" : factory ? "Ready" : "Deploy"} onClick={() => setMessage(missing.length ? `Missing: ${missing.join(", ")}` : factory ? `Factory ready: ${factory}` : "Use the deployment button below with your protocol administrator wallet.")} /></div>{!factory && <button disabled={bootstrapping || missing.length > 0} onClick={() => void boot()} className="mt-5 rounded-xl bg-mint px-4 py-2.5 text-[11px] font-bold text-ink shadow-mint transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50">{bootstrapping ? "Awaiting Freighter confirmations…" : "Deploy Meridian protocol with Freighter"}</button>}{session && <button onClick={() => { disconnect(); setMessage("Disconnected from Meridian. Freighter permissions remain under your control in the extension."); }} className="ml-0 mt-3 rounded-xl bg-coral/10 px-4 py-2.5 text-[11px] font-bold text-coral ringline transition hover:bg-coral hover:text-ink sm:ml-3 sm:mt-5">Disconnect from Meridian</button>}{message && <motion.p initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} className="mt-5 flex items-center gap-2 break-all rounded-xl bg-mint/10 px-4 py-3 text-[11px] text-mint ringline"><CheckCircle2 size={14} className="shrink-0" />{message}</motion.p>}</div>;
}
function Setting({ icon, title, detail, action, onClick }: { icon: React.ReactNode; title: string; detail: string; action: string; onClick: () => void }) { return <button onClick={onClick} className="flex w-full items-center gap-3 rounded-2xl bg-surface/50 p-4 text-left ringline soft-card transition hover:-translate-y-0.5 hover:bg-surface/70"><span className="grid h-9 w-9 place-items-center rounded-xl bg-mint/12 text-mint">{icon}</span><span className="flex-1"><span className="block text-[12px] font-bold">{title}</span><span className="mt-1 block text-[10px] text-white/45">{detail}</span></span><span className="text-[11px] font-semibold text-mint">{action}</span></button>; }
